"""users

Revision ID: 0e9e87d2a663
Revises: bb819e3dc83c
Create Date: 2020-04-06 11:30:07.711025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9e87d2a663'
down_revision = 'bb819e3dc83c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
